# Generated by Django 4.2.20 on 2026-03-15 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kmr', models.CharField(max_length=100, verbose_name='Kurmanci')),
                ('name_de', models.CharField(max_length=100, verbose_name='Almanca')),
                ('name_en', models.CharField(max_length=100, verbose_name='İngilizce')),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kmr', models.CharField(max_length=200, verbose_name='Kurmanci başlık')),
                ('title_de', models.CharField(max_length=200, verbose_name='Almanca başlık')),
                ('title_en', models.CharField(max_length=200, verbose_name='İngilizce başlık')),
                ('description_kmr', models.TextField(blank=True, verbose_name='Kurmanci açıklama')),
                ('description_de', models.TextField(blank=True, verbose_name='Almanca açıklama')),
                ('description_en', models.TextField(blank=True, verbose_name='İngilizce açıklama')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Destpêk / Anfänger / Beginner'), (2, 'Navîn / Mittelstufe / Intermediate'), (3, 'Pêşketî / Fortgeschritten / Advanced')], default=1)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='lessons/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lessons.category')),
            ],
            options={
                'verbose_name': 'Ders',
                'verbose_name_plural': 'Dersler',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kmr', models.CharField(max_length=200, verbose_name='Kurmanci')),
                ('pronunciation', models.CharField(blank=True, max_length=200, verbose_name='Telaffuz')),
                ('audio_kmr', models.FileField(blank=True, null=True, upload_to='audio/words/kmr/')),
                ('de', models.CharField(max_length=200, verbose_name='Almanca')),
                ('en', models.CharField(max_length=200, verbose_name='İngilizce')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/words/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='lessons.lesson')),
            ],
            options={
                'verbose_name': 'Kelime',
                'verbose_name_plural': 'Kelimeler',
                'ordering': ['order'],
            },
        ),
    ]
