# Generated by Django 4.2.20 on 2026-03-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['category', 'level', 'order'], 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['order'], 'verbose_name': 'Word', 'verbose_name_plural': 'Words'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name_de',
            field=models.CharField(max_length=100, verbose_name='German'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='English'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_kmr',
            field=models.CharField(max_length=100, verbose_name='Kurmanji'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description_de',
            field=models.TextField(blank=True, verbose_name='German description'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='English description'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description_kmr',
            field=models.TextField(blank=True, verbose_name='Kurmanji description'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'A1 — Destpêk'), (2, 'A2 — Destpêkê Bilind'), (3, 'B1 — Navîn'), (4, 'B2 — Navînê Bilind'), (5, 'C1 — Pêşketî'), (6, 'C2 — Pispor')], default=1),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title_de',
            field=models.CharField(max_length=200, verbose_name='German title'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title_en',
            field=models.CharField(max_length=200, verbose_name='English title'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title_kmr',
            field=models.CharField(max_length=200, verbose_name='Kurmanji title'),
        ),
        migrations.AlterField(
            model_name='word',
            name='de',
            field=models.CharField(max_length=200, verbose_name='German'),
        ),
        migrations.AlterField(
            model_name='word',
            name='en',
            field=models.CharField(max_length=200, verbose_name='English'),
        ),
        migrations.AlterField(
            model_name='word',
            name='kmr',
            field=models.CharField(max_length=200, verbose_name='Kurmanji'),
        ),
        migrations.AlterField(
            model_name='word',
            name='pronunciation',
            field=models.CharField(blank=True, max_length=200, verbose_name='Pronunciation'),
        ),
    ]
