# Generated by Django 4.2.20 on 2026-03-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_category_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='emoji',
            field=models.CharField(blank=True, max_length=10, verbose_name='Emoji'),
        ),
    ]
