# Generated by Django 4.2.20 on 2026-03-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_word_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='audience',
            field=models.CharField(choices=[('child', 'Kinder / Children'), ('adult', 'Erwachsene / Adults'), ('both', 'Alle / Both')], default='both', max_length=10, verbose_name='Zielgruppe'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='audience',
            field=models.CharField(choices=[('child', 'Kinder / Children'), ('adult', 'Erwachsene / Adults'), ('both', 'Alle / Both')], default='both', max_length=10, verbose_name='Zielgruppe'),
        ),
    ]
