# Generated by Django 4.2.20 on 2026-03-15 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('multiple_choice', 'Çoktan Seçmeli'), ('matching', 'Eşleştirme'), ('fill_blank', 'Boşluk Doldurma'), ('listen_select', 'Dinle ve Seç')], max_length=20)),
                ('question_lang', models.CharField(choices=[('kmr', 'Kurmanci'), ('de', 'Almanca'), ('en', 'İngilizce')], default='de', max_length=3, verbose_name='Soru dili')),
                ('question', models.TextField(verbose_name='Soru')),
                ('question_audio', models.FileField(blank=True, null=True, upload_to='audio/questions/')),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='images/questions/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('stars', models.PositiveSmallIntegerField(default=1)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='lessons.lesson')),
            ],
            options={
                'verbose_name': 'Alıştırma',
                'verbose_name_plural': 'Alıştırmalar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('kmr', 'Kurmanci'), ('de', 'Almanca'), ('en', 'İngilizce')], default='kmr', max_length=3)),
                ('text', models.CharField(max_length=300)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/choices/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/choices/')),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='exercises.exercise')),
            ],
            options={
                'verbose_name': 'Seçenek',
                'verbose_name_plural': 'Seçenekler',
                'ordering': ['order'],
            },
        ),
    ]
