# Generated by Django 4.2.20 on 2026-03-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='plan_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='interface_lang',
            field=models.CharField(choices=[('de', 'Deutsch'), ('en', 'English')], default='de', max_length=2, verbose_name='Interface language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('child', 'Child / Zarok'), ('parent', 'Parent / Dêûbav')], default='child', max_length=10),
        ),
    ]
