# Generated by Django 4.2.20 on 2026-03-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='audience',
            field=models.CharField(choices=[('child', 'Kinder / Children'), ('adult', 'Erwachsene / Adults')], default='child', max_length=10, verbose_name='Zielgruppe / Target audience'),
        ),
    ]
